[build]
  # Build command - uses npm/yarn to build the Vite project
  command = "npm run build"

  # Publish directory - where Vite outputs the built files
  publish = "dist"

[build.environment]
  # Node.js version for build environment
  NODE_VERSION = "18"
  # Environment variables for build process
  # The GEMINI_API_KEY will be set in Netlify dashboard
  # Vite will pick it up during build and inject it into the client bundle

# Redirects for Single Page Application (SPA)
# This ensures all routes are handled by the React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for enhanced security
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - adjust as needed for your external dependencies
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://esm.sh;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tailwindcss.com;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://generativelanguage.googleapis.com;
      img-src 'self' data: blob:;
      media-src 'self' blob:;
    '''
    # Other security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "microphone=(), camera=(), geolocation=()"

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache manifest and service worker with shorter cache time
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# PWA specific headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
